<a href="https://colab.research.google.com/github/Samarthb1257/Lab_Project/blob/main/25_27_APRIL_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import json
emp_dict={
    "ERP":"YOU",9:"ERP",8.9:"python"
}
print(emp_dict)

{'ERP': 'YOU', 9: 'ERP', 8.9: 'python'}


In [ ]:
import json
x={
    "x": "10",
    "y": 56,
    "z": "python"
}
y=json.dumps(x)
print(y)

{"x": "10", "y": 56, "z": "python"}


In [ ]:
def outer():
  print("Outer Function ")

  def inner():
    print("Inner Function")

  inner()

outer()

Outer Function 
Inner Function


In [ ]:
def add():
  a=10
  b=20
  c=a+b
  print(c)

  def sub():
    a=30
    b=10
    c=a-b
    print(c)

  sub()

add()

30
20


In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])

x= arr.copy()
y= arr.view()
#z= arr.cut()
arr[1]=42
arr[0]=45

print(arr)
print(x)
print(y)
#print(z)


[45 42  3  4  5]
[1 2 3 4 5]
[45 42  3  4  5]


In [ ]:
import numpy as np

x= np.array([[1,2],[4,5]])
y= np.array([[6,7],[9,10]])

print("Addition Of Matrix ")
print(np.add(x,y))

print("Subtraction Of Matrix ")
print(np.subtract(x,y))


Addition Of Matrix 
[[ 7  9]
 [13 15]]
Subtraction Of Matrix 
[[-5 -5]
 [-5 -5]]


In [ ]:
l1=np.matrix('1,2,3 ; 4,5,6 ; 7,8,9')
a=np.array(l1)
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
l1=np.matrix('1,2,3 ; 4,5,6 ; 7,8,9')
a=np.array(l1)
print(a.T)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# Lambda function
def get_cube(num):
  return num*num*num
print(get_cube(5))


#Lambda program

res= lambda num:num*num*num
print(res(5))

125
125
