<a href="https://colab.research.google.com/github/Samarthb1257/Lab_Project/blob/main/25_5_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Array operations in python

import pandas as pd
import numpy as np

df = pd.read_excel('/ARRAY .xlsx',header=None)
df1 = pd.read_excel('/ARRAY 1 .xlsx',header=None)

array = df.to_numpy()
array1 = df1.to_numpy()

print(array)
print(array1)

[['name' 'roll no.' 'marks']
 ['A' 1 20]
 ['B' 2 30]
 ['C' 3 20]
 ['D' 4 40]
 ['E' 5 50]
 ['F' 6 60]
 ['G' 7 52]
 ['H' 8 80]
 ['I' 9 63]
 ['J' 10 26]
 ['K' 11 23]
 ['L' 12 28]
 ['M' 13 90]]
[['name' 'roll no.' 'marks']
 ['A' 1 20]
 ['B' 2 30]
 ['C' 3 20]
 ['D' 4 40]
 ['E' 5 50]
 ['F' 6 60]
 ['G' 7 52]
 ['H' 8 80]
 ['I' 9 63]
 ['J' 10 26]
 ['K' 11 23]
 ['L' 12 28]
 ['M' 13 90]]


In [ ]:
a= np.vstack(array)
print(a)


[['name' 'roll no.' 'marks']
 ['A' 1 20]
 ['B' 2 30]
 ['C' 3 20]
 ['D' 4 40]
 ['E' 5 50]
 ['F' 6 60]
 ['G' 7 52]
 ['H' 8 80]
 ['I' 9 63]
 ['J' 10 26]
 ['K' 11 23]
 ['L' 12 28]
 ['M' 13 90]]


In [ ]:
b= np.hstack(array1)
print(b)

['name' 'roll no.' 'marks' 'A' 1 20 'B' 2 30 'C' 3 20 'D' 4 40 'E' 5 50
 'F' 6 60 'G' 7 52 'H' 8 80 'I' 9 63 'J' 10 26 'K' 11 23 'L' 12 28 'M' 13
 90]


In [ ]:
c=np.dstack(array)
print(c)


[[['name' 'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M']
  ['roll no.' 1 2 3 4 5 6 7 8 9 10 11 12 13]
  ['marks' 20 30 20 40 50 60 52 80 63 26 23 28 90]]]


In [ ]:
array = np.random.randint(0,3,(20,20))
zeros = np.sum(array == 0)
ones = np.sum(array == 1)
twos = np.sum(array == 2)

print(zeros)
print(ones)
print(twos)

arr_stacked = np.stack([array,array])
print('Numpy horizontal stacking method #1')
print('=========================================')
print(arr_stacked)

123
135
142
Numpy horizontal stacking method #1
[[[1 2 2 1 2 1 0 1 1 1 0 1 0 0 1 0 2 1 2 0]
  [0 2 2 1 1 0 2 1 2 2 2 0 0 0 1 2 0 0 1 2]
  [0 1 1 2 1 0 0 2 2 0 2 2 2 1 0 2 0 0 2 1]
  [1 1 0 0 1 1 2 2 1 1 2 0 2 2 1 1 0 2 0 2]
  [2 2 1 1 0 1 2 2 1 1 2 1 1 2 0 2 1 2 2 1]
  [2 1 0 2 0 0 0 2 2 2 2 0 0 2 2 1 2 1 2 1]
  [2 0 2 2 0 0 2 1 0 2 1 0 2 1 2 1 0 0 2 2]
  [2 0 2 1 1 2 1 1 2 0 2 0 1 2 2 0 2 0 1 2]
  [1 1 0 2 1 0 2 2 1 1 1 1 2 2 1 2 0 1 2 1]
  [0 0 0 1 0 1 1 2 1 2 0 2 1 1 2 0 2 1 2 1]
  [0 1 0 2 0 1 2 0 1 2 0 1 2 2 0 1 0 1 0 2]
  [1 0 0 1 1 2 1 2 0 1 0 1 1 2 1 2 1 1 2 1]
  [2 2 0 0 0 1 0 1 1 2 0 2 2 0 1 2 1 0 2 1]
  [1 2 0 2 0 2 1 0 2 0 2 2 0 0 1 2 0 1 2 1]
  [1 0 2 2 0 0 0 2 1 0 1 1 0 1 2 0 2 2 1 2]
  [2 1 0 0 0 0 2 2 0 0 0 1 1 0 0 1 2 0 0 0]
  [2 0 0 2 1 1 0 2 0 1 2 2 2 1 2 2 0 0 2 1]
  [0 0 1 1 0 0 0 2 0 1 0 2 1 1 2 2 1 1 1 0]
  [1 2 2 0 2 1 2 0 1 1 2 1 1 2 2 2 0 2 2 1]
  [1 0 1 1 2 1 1 0 0 0 2 2 1 1 0 0 1 2 0 1]]

 [[1 2 2 1 2 1 0 1 1 1 0 1 0 0 1 0 2 1 2 0]
  [0 2 2 1 1 0 2 1 2 2 2 0

In [ ]:
import csv

product_list = []

with open('/content/Sales .CSV', 'r') as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    for row in reader:
        product_list.append(row[1])  # Assuming the product name is in the second column (index 1)

# Print the product list
print("Product List:")
for product in product_list:
    print(product)


Product List:
Lenovo Laptop
Samsung M31
Realmi 10pro
Oppo F21
Lenovo Laptop
Samsung M31
LG TV 32"
Oppo F21
Lenovo Laptop
Samsung M31
LG TV 32"
Lenovo Laptop
Samsung M31
Realmi 10pro
Lenovo Laptop
Oppo F21
LG TV 32"
Lenovo Laptop
Samsung M31
LG TV 32"


In [ ]:
import csv

supplier_dict = {}

with open('/content/Sales .CSV', 'r') as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    for row in reader:
        supplier = row[2]  # Assuming supplier details are in the second column (index 1)
        if supplier not in supplier_dict:
            supplier_dict[supplier] = {}

# Print the supplier details
print("Supplier Details:")
for supplier in supplier_dict:
    print("Supplier:", supplier)


Supplier Details:
Supplier: Raka Ele.
Supplier: Vijay Sales
Supplier: Gada Ele.
Supplier: Surya Ele.
Supplier: Deshmukh sales


In [ ]:
import csv

customer_tuple = ()

with open('/content/Sales .CSV', 'r') as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    for row in reader:
        customer_name = row[3]  # Assuming customer names are in the second column (index 1)
        customer_tuple += (customer_name,)

# Print the customer details
print("Customer Names:")
for customer_name in customer_tuple:
    print(customer_name)


Customer Names:
Kaustubh Mahajan
Siddhi Kiwale
Sanket Kandalkar
Yash Mali
Yash Bagul
Siddhi Kiwale
Sanket Kandalkar
Kaustubh Mahajan
Yash Mali
Siddhi Kiwale
Sanket Kandalkar
Kaustubh Mahajan
Yash Mali
Siddhi Kiwale
Tanuja Mali
Kaustubh Mahajan
Sanket Kandalkar
Siddhi Kiwale
Kaustubh Mahajan
Yash Mali


In [ ]:
import csv

supplier_dict = {}

with open('/content/Sales .CSV', 'r') as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    for row in reader:
        supplier = row[2]  # Assuming supplier details are in the third column (index 2)
        if supplier not in supplier_dict:
            supplier_dict[supplier] = None

# Print the supplier names
print("Supplier Names:")
for supplier in supplier_dict.keys():
    print(supplier)


Supplier Names:
Raka Ele.
Vijay Sales
Gada Ele.
Surya Ele.
Deshmukh sales


In [ ]:
import csv
import statistics
f1=open("/content/Sales .CSV","r")
data1=list(csv.reader(f1))
print(data1)
prodetails=[]
for i in range(len(data1)):
  prodetails.append(data1[i][1])
print(prodetails)
ID=[]
for i in range(len(data1)):
  ID.append(data1[i][0])
print(ID)
suppdetails=[]
for i in range(len(data1)):
  suppdetails.append(data1[i][2])
SuppDetails={}
for i in range(1,len(data1)):
  SuppDetails.update({ID[i]:suppdetails[i]})
print(SuppDetails)
CustDetails=[]
for i in range(1,len(data1)):
  CustDetails.append(data1[i][3])
print(tuple(CustDetails))
gender=[]
for i in range(len(data1)):
  gender.append(data1[i][4])
print(gender)
for i in range(len(data1)):
  prodetails.append(data1[i][1])
print(prodetails)
suppdetails=list(SuppDetails.values())
print("The most popular product for sales is",statistics.mode(prodetails))
print("The best supplier for sales is",statistics.mode(suppdetails))
CustDet=list(CustDetails)
print(CustDet)
print("The customer who buys most of the product is",statistics.mode(CustDet))
count=0
for i in range(len(gender)):
  if gender[i]== "Female":
    count+=1
print("The Number of customers who are female are",count)

[['Product ID', 'Product details', 'Supplier Details', 'Customer Details', 'Gender'], ['P00001', 'Lenovo Laptop', 'Raka Ele.', 'Kaustubh Mahajan', 'Male'], ['P00002', 'Samsung M31', 'Vijay Sales', 'Siddhi Kiwale', 'Female'], ['P00003', 'Realmi 10pro', 'Gada Ele.', 'Sanket Kandalkar', 'Male'], ['P00004', 'Oppo F21', 'Surya Ele.', 'Yash Mali', 'Male'], ['P00005', 'Lenovo Laptop', 'Raka Ele.', 'Yash Bagul', 'Male'], ['P00006', 'Samsung M31', 'Gada Ele.', 'Siddhi Kiwale', 'Female'], ['P00007', 'LG TV 32"', 'Vijay Sales', 'Sanket Kandalkar', 'Male'], ['P00008', 'Oppo F21', 'Surya Ele.', 'Kaustubh Mahajan', 'Male'], ['P00009', 'Lenovo Laptop', 'Raka Ele.', 'Yash Mali', 'Male'], ['P00010', 'Samsung M31', 'Gada Ele.', 'Siddhi Kiwale', 'Female'], ['P00011', 'LG TV 32"', 'Surya Ele.', 'Sanket Kandalkar', 'Male'], ['P00012', 'Lenovo Laptop', 'Raka Ele.', 'Kaustubh Mahajan', 'Male'], ['P00013', 'Samsung M31', 'Surya Ele.', 'Yash Mali', 'Male'], ['P00014', 'Realmi 10pro', 'Raka Ele.', 'Siddhi Kiwal

In [ ]:
Vegetables=float(input())
Grocery=float(input())
Dailyneeds=float(input())

if Vegetables > 500:
    print("Sorry, She will not buy daily needs .")
elif Vegetables == Grocery== Dailyneeds== 166.66:
    print("She can buy all three items.")

else:
    print("She has to do some changes in budget.")

456
45
7
She has to do some changes in budget.
